version: 1
disable_existing_loggers: true
formatters:
  verbose:
    class: 'logging.Formatter'
    format: '[%(levelname)s] %(asctime)s - %(name)s - %(funcName)s:%(lineno)d: %(message)s'
handlers:
  console:
    level: 'DEBUG'
    class: 'logging.StreamHandler'
    formatter: 'verbose'
    stream : 'ext://sys.stdout'
  file_handler:
    level: 'INFO'
    class: 'logging.handlers.WatchedFileHandler'
    formatter: 'verbose'
    filename: 'logs/raysa_flask.log'
    mode: 'a'
    encoding: 'utf-8'
loggers:
  app: # app logger
    level: 'DEBUG'
    propagate: false
    handlers:
      - 'console'
      - 'file_handler'
  requests:
    level: 'WARNING'
root:
  level: 'DEBUG'
  handlers:
    - 'console'
    - 'file_handler'
