version: 1
# disable_existing_loggers: false
formatters:
  hiformat:
    format: '[%(levelname)s] - %(asctime)s - %(name)s on %(lineno)d - %(message)s'
  simple:
    format: '[%(levelname)s] - %(asctime)s - %(name)s - %(message)s'
handlers:
  app_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: hiformat
    stream: ext://sys.stdout
  werkzeug_console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    maxBytes: 20971520 # 20 MB
    backupCount: 3
    filename: logs/dev_flask.log
    mode: 'a'
    encoding: 'utf-8'
  werkzeug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    maxBytes: 10485760 # 10 MB
    backupCount: 2
    filename: logs/werkzeug_flask.log
    mode: 'a'
    encoding: 'utf-8'
loggers:
  app:
    level: DEBUG
    handlers: [app_console, app_file]
    propagate: no
  console:
    level: DEBUG
    handlers: [app_console]
    propagate: no
  app_file:
    level: DEBUG
    handlers: [app_file]
    propagate: no
  flask: # notice no formatters declared
    level: DEBUG
    propagate: no
  werkzeug: # notice no formatters declared
    level: DEBUG
    handlers: [werkzeug_file, werkzeug_console]
    propagate: no
root:
  level: DEBUG
  handlers: [app_console, app_file]
