version: 1
disable_existing_loggers: true
formatters:
  hiformat:
    format: '[%(levelname)s] - %(asctime)s - %(name)s on %(lineno)d - %(message)s'
  simple:
    format: '[%(levelname)s] - %(asctime)s - %(name)s - %(message)s'
handlers:
  app_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: hiformat
    stream: ext://sys.stdout
  werkzeug_console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  app_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/dev_flask.log
    mode: 'a'
    encoding: 'utf-8'
  werkzeug_file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/werkzeug_flask.log
    mode: 'a'
    encoding: 'utf-8'
loggers:
  app:
    level: DEBUG
    handlers: [app_console, app_file]
    propagate: no
  console:
    level: DEBUG
    handlers: [app_console]
    propagate: no
  # app_file:
  #   level: DEBUG
  #   handlers: [app_file]
  #   propagate: no
  #
  # werkzeug:
  #   level: DEBUG
  #   handlers: [werkzeug_file, werkzeug_console]
  #   propagate: no
root:
  level: DEBUG
  handlers: [app_console, app_file]
